[template.environment]
  MORALIS_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6ImUwMjkxZjYwLTM4YjgtNDFmMS04ZGY5LWRmNGRjMTZiM2YyMSIsIm9yZ0lkIjoiMzkzMzc0IiwidXNlcklkIjoiNDA0MjA4IiwidHlwZUlkIjoiMTBjNTEyMzctMmU2MS00OTE0LTgzODctMTE3OTk2Mjg3NzJlIiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3MTY0NDUyMTcsImV4cCI6NDg3MjIwNTIxN30.Cv1Na1ZJrC3Oh4mkUA_Dpia1d7a98kx3cHMtcNUasp4"
  NEXTAUTH_SECRET = "b5dc432beb8ee422c0b844e376fb587b"
